### ISSUE TITLE
"The system cannot find the file specified" when running out of the box on Windows

### ISSUE THREAD

**Issue by charlotte-murray** [quarckster/nmf_to_wav#4]
Hi, I'm not a python expert so I am struggling to work out why this isn't working for me. I am running this out of the box and getting the below error - should I be doing something different? I'm on Windows 10, and python 2.7.

```
λ python nmf_converter.py "C:\path\to\my\file.nmf"
Traceback (most recent call last):
  File "nmf_converter.py", line 121, in <module>
    convert_to_wav(path_to_file)
  File "nmf_converter.py", line 109, in convert_to_wav
    stdin=subprocess.PIPE
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by charlotte-murray** [comment]
Have worked out what the problem was - I didn't have the ffmpeg cli installed and I've put the ffmpeg.exe file in the directory I was running the script from
